---
# Kubernetes CLI tools defaults
kubernetes_helm_url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
kubernetes_k9s_url: https://github.com/derailed/k9s/releases/latest/download/k9s_Linux_amd64.tar.gz
