---
- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ 'noble' if ansible_facts['distribution_release'] == 'resolute' else ansible_facts['distribution_release'] }} stable"
    state: present
    filename: docker
  become: true

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Add user to docker group
  user:
    name: "{{ workstation_user }}"
    groups: docker
    append: true

- name: Enable Docker service
  systemd:
    name: docker
    enabled: true
    state: started
